apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-api
  labels:
    app: employee-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-api
  template:
    metadata:
      name: employee-api
      labels:
        app: employee-api
    spec:
      containers:
        - name: employee-api
          image: plaam/fleetjourney-employee-api:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: "ASPNETCORE_ENVIRONMENT"
              value: "Production"
            - name: "AZURE_CLIENT_ID"
              valueFrom:
                secretKeyRef:
                  key: "azure-client-id"
                  name: "azure-key-vault"
            - name: "AZURE_CLIENT_SECRET"
              valueFrom:
                secretKeyRef:
                  key: "azure-client-secret"
                  name: "azure-key-vault"
            - name: "AZURE_TENANT_ID"
              valueFrom:
                secretKeyRef:
                  key: "azure-tenant-id"
                  name: "azure-key-vault"
            - name: "AZURE_VAULT_NAME"
              valueFrom:
                secretKeyRef:
                  key: "azure-vault-name"
                  name: "azure-key-vault"
      restartPolicy: Always
      